### ISSUE TITLE
Fout afvanging

### ISSUE THREAD

**Issue by evaleffef** [Amsterdam/makkelijkemarkt-kiesjekraam#358]
Niet alle paden bij fouten zijn helder.
Foutmeldingen registreren

**Comment by tjoekbezoer** [comment]
Er zit veel inconsistentie in het afhandelen van fouten. Twee observaties:

### 1. Fout wordt afgehandeld in index.ts

In onderstaande code is te zien dat de foutafhandeling binnen de route definitie wordt afgehandeld. `getSollicitantenlijstInput` wordt aangeroepen, en indien dit fout gaat wordt het fout object naar de client gestuurd (met een `Response.end` call, waar beter een `Response.send` gebruikt kan worden [per advies van express zelf](https://expressjs.com/en/api.html#res.end))

https://github.com/Amsterdam/fixxx-pakjekraam/blob/bbae18a3305fc43949d17c7ffedf7eba8dd0791b/src/index.ts#L239-L255

Dit gebeurt in dit bestand met grote regelmaat.


### 2. Fout wordt afgehandeld in functie binnen `routes` folder

Een ander veel voorkomende methode is dat de fout al in een functie wordt afgehandeld voordat hij wordt toegepast in een route definitie.

https://github.com/Amsterdam/fixxx-pakjekraam/blob/bbae18a3305fc43949d17c7ffedf7eba8dd0791b/src/index.ts#L477-L483

In de `marketApplicationPage` functie (`routes/market-application.ts`) wordt in de foutafhandeling vervolgens een functie uit `express.utils.ts` aangeroepen:

https://github.com/Amsterdam/fixxx-pakjekraam/blob/bbae18a3305fc43949d17c7ffedf7eba8dd0791b/src/routes/market-application.ts#L20-L25

`internalServerErrorPage` is te vinden in `express-utils.ts`:

https://github.com/Amsterdam/fixxx-pakjekraam/blob/bbae18a3305fc43949d17c7ffedf7eba8dd0791b/src/express-util.ts#L35-L38

Deze functie lijkt vervolgens heel erg op de middleware die in `index.ts` wordt gedefinieerd om ongevangen errors af te vangen:

https://github.com/Amsterdam/fixxx-pakjekraam/blob/bbae18a3305fc43949d17c7ffedf7eba8dd0791b/src/index.ts#L771-L774

### Conclusie

Afhankelijk van waar de fout optreedt wordt een ander codepad bewandeld met waarschijnlijk andere uitkomsten. Dit zijn slechts twee voorbeelden, het zou me niet verbazen als er nog meer manieren zijn om een fout af te handelen (of niet af te handelen).

In mijn ogen moet dit allemaal op één manier afgehandeld worden, waarbij `NODE_ENV` en/of de permissions van de ingelogde user bepaald of de details van de error naar de client gestuurd moeten worden (zodat een ontwikkelaar de fout kan debuggen indien nodig).

Persoonlijk lijkt het me geschikt om aan het einde een error middleware toe te voegen (wat nu ook al gebeurd) die dit regelt. Vervolgens kan er in elke route definitie een `catch(next)` toegevoegd worden, of als het echt nodig is een custom afhandeling geschreven worden.
