### ISSUE TITLE
Ondernemer blokkeren

### ISSUE THREAD

**Issue by evaleffef** [Amsterdam/makkelijkemarkt-kiesjekraam#365]
Een ondernemer moet geblokkeerd kunnen worden.
Bijvoorbeeld - ondernemer wordt niet meer meegenomen in de indeling, of ondernemer kan ook niet meer inloggen.

Work around: je kunt nu bij een ondernemer invullen dat hij langere tijd afwezig is.

**Comment by Carlio75** [comment]
Ha Jacqueline,

Ondernemers die niet betalen, of om een andere reden, wil de markt op non actief kunnen zetten. Dit betekend dat ondernemers zelf geen acties meer kunnen doen in Kies je Kraam en niet mee gaan in de indeling.

Even kort hoe ik nu voor me zie wat er dan moet gebeuren:

View marktbeheerder
- de marktbeheerder moet de ondernemer op non actief kunnen zetten. hier hoeft geen begin- en of einddatum aan te zitten. - Een ondernemer is standaard actief, en kan met een checkbox op non-actief gezet worden
- de ondernemer is op alle markten non-actief, dit is dus niet instelbaar per markt
- de marktbeheerder moet een plek hebben waar hij (per markt) kan zien welke ondernemer er op non-actief staat.

View marktmeester
- de marktmeester moet een plek hebben waar hij (per markt) kan zien welke ondernemer er op non-actief staat.
- de marktmeester kan de ondernemer NIET op non-actief zetten, dit mag alleen de rol van de marktmeester.
- de marktmeester kan geen dagen etc selecteren voor een ondernemer die op non-actief staat.

View ondernemer
de ondernemer kan zichzelf NIET op non-actief zetten, dit mag alleen de rol van de marktmeester.
- de ondernemer kan nog wel inloggen maar krijgt daarna op zijn dashboard een melding te zien dat hij/zij op non-actief staat en contact moet opnemen met het marktbureau/marktmeester om weer op een markt te kunnen staan
- los van het inloggen kan een ondernemer die op non-actief staat niets meer doen in Kies je Kraam. Dus geen markten bekijken, geen dagen selecteren etc.

Indelingsberekening
Ondernemers die op non-actief staan worden NIET meegenomen in de indelingsberekening, en worden dus niet ingedeeld op markten.

**Comment by Carlio75** [comment]
Deze wens is weer actueel geworden

**Comment by Carlio75** [comment]
Akkoord op uitrol, wacht op laatste info van de markt mbt proces

**Comment by Carlio75** [comment]
@tjoekbezoer dit is goedgekerud door de gemeente, wil jij dit ticket oppakken?

**Comment by Carlio75** [comment]
Hi,

Na overleg met Marjolein is het volgende besloten. Het blokkeren van ondernemers wordt op termijn in Makkelijke Markt mogelijk gemaakt. Maar eerst dient Makkelijke Markt te ‘verhuizen’ en pas dan kunnen weer aanvullingen/wijzigingen worden gedaan. Laura neemt dit mee in de wijzigingen Makkelijke Markt na verhuizing naar een andere server. Vooralsnog kunnen ondernemers in Kies je kraam op ‘langdurig afwezig’ gezet worden waardoor zij niet meer kunnen meedoen met digitaal indelen.

Wordt vervolgd.

Hartelijke groet,

 

Jacqueline van Norden
