### ISSUE TITLE
Alle aangemelde ondernemers mailen

### ISSUE THREAD

**Issue by tomootes** [Amsterdam/makkelijkemarkt-kiesjekraam#525]
Indien een markt is afgezegd, zou je **alle aangemelde ondernemers** een alternatieve mail willen sturen.

## Aanleiding
**Dag blokkeren #445**

## Mogelijk MVP
Export van aangemelde ondernemers (inclusief e-mailadressen) want dan kan er handmatig een e-mail gestuurd worden en eventueel ondernemers zonder e-mailadres kunnen opgebeld worden.

**Comment by tomootes** [comment]
@evaleffef even een overdenking. Wie gaan we precies mailen? Iedereen die ingeschreven staat op een bepaalde markt? Alle VPHS? Alle sollicitanten die zich hebben aangemeld?

**Comment by evaleffef** [comment]
@tomootes nu gaan we nog GEEN mailfunctie maken. Focus ligt nu op 'uitzetten' van standaard niet marktdagen zoals de feestdagen. De hele issue wat te doen bij calamiteiten moeten we nog met de markt bespreken hoe ze dit willen
