### ISSUE TITLE
Extra status markt toevoegen: on-hold/pauze

### ISSUE THREAD

**Issue by evaleffef** [Amsterdam/makkelijkemarkt-kiesjekraam#663]
Omdat er nu tijdelijk niet digitaal wordt ingedeeld, vult een marktbeheerder elke dag in Makkelijke Markt een datum in om de markt op die dag te blokkeren.

Dit is bewerkelijk en foutgevoelig. 

Voorstel is om een extra status markt toe te voegen: on-hold/pauze.

Als een markt deze status heeft werkt het zelfde als live - maar er draait geen indeling en dus worden er ook geen mails verstuurd.

Graag hierover meedenken.

**Comment by tjoekbezoer** [comment]
Is er niet al een status die gebruikt kan worden hiervoor? De indeling wordt alleen gedraaid voor markten in de fase `live` of `wenperiode`. Ik zie dat er ook nog een `activatie` status is (of `activate`? Lijkt een typfout in de code).

Is die niet te gebruiken voor deze tijdelijk situatie?

**Comment by evaleffef** [comment]
Nope, dat is een andere fase, waar andere meldingen in het systeem zichtbaar worden, dus niet handig.

**Comment by tjoekbezoer** [comment]
In dat geval lijkt me het toevoegen van een 'gepauzeerd' status een prima optie. Dit is iets wat in MM geïmplementeerd moet worden lijkt me. De indeling zal hier automatisch goed mee omspringen, omdat enkel `live` en `wenperiode` markten doorgerekend worden.

**Comment by tjoekbezoer** [comment]
Een andere optie is overigens de CRON job uitzetten. Kleine moeite, zelfde effect.

**Comment by evaleffef** [comment]
De status voorbereiding wordt zeker gebruikt: in deze fase is de markt wél zichtbaar voor de marktmeester, maar nog niet voor de ondernemer. 

CRON job uitzetten zou ook kunnen, maar dan is de markt afhankelijk van ons om dat te doen, dus korte termijn oplossing.

**Comment by Carlio75** [comment]
@Carlio75 Vraag ook of Maarten van Makkelijke Markt de optie "Pauze" toevoegt. EN pas de Wiki aan!

**Comment by Carlio75** [comment]
deze even on hold, laten we eerst even focussen op de bugs op acceptatie.

**Comment by Carlio75** [comment]
MM applicatie ontwikkeling ligt momenteel stil bij Datapunt, we kunnen dit ticket niet oppakken.
