### ISSUE TITLE
Tijdstip draaien aanpassen naar 21.00 uur

### ISSUE THREAD

**Issue by Carlio75** [Amsterdam/makkelijkemarkt-kiesjekraam#688]
We draaien nu de nieuwe markt voor de volgende dag om 00.00 uur, dit moet worden vervroegd naar 21.00 uur.

**Comment by tomootes** [comment]
@Carlio75 Ik heb hier in de code het tijdstip aangepast en in de beide cronjobs voor de indeling én het versturen van de mailtjes.

**Comment by Carlio75** [comment]
@tjoekbezoer zou je dit naar productie kunnen pushen als je de rechten hebt?
