### ISSUE TITLE
Niet alle voorkeuren zichtbaar in Toewijzingen/afwijzingen

### ISSUE THREAD

**Issue by Carlio75** [Amsterdam/makkelijkemarkt-kiesjekraam#711]
Als een ondernemer aangeeft dat hij/zij met een EVI komt, wordt dit niet meegenomen in het toewijzingen/afwijzingen overzicht. 

Zie bijgesloten voorbeeld van PROD.

LET OP: check even of BAK wel goed meekomt. Flex komt wel goed mee.

De logica werkt trouwens wel goed. Deze ondernemer heeft geen plek gekregen omdat er geen EVI plaatsen beschikbaar waren.

<img width="1053" alt="Screenshot 2020-09-23 at 11 47 11" src="https://user-images.githubusercontent.com/64955526/93996829-012d7e80-fd93-11ea-9c6d-bc8f03839ac3.png">

Ander voorbeeld op PROD: https://kiesjekraam.amsterdam.nl/ondernemer/2019052204/toewijzingen-afwijzingen

**Comment by Carlio75** [comment]
Getest voor woensdag 2 december:
https://acc.kiesjekraam.amsterdam.nl/markt/126/2020-12-02/concept-indelingslijst/

https://acc.kiesjekraam.amsterdam.nl/ondernemer/2008020401/algemene-voorkeuren/126/
https://acc.kiesjekraam.amsterdam.nl/ondernemer/1999010403/algemene-voorkeuren/126/
BAK en EVI aangezet  (staat op bakplek)

https://acc.kiesjekraam.amsterdam.nl/ondernemer/2006011003/algemene-voorkeuren/126/
https://acc.kiesjekraam.amsterdam.nl/ondernemer/1991050304/algemene-voorkeuren/126/
EVI aangezet  (staat op gewone plek)

https://acc.kiesjekraam.amsterdam.nl/profile/1966061702/
https://acc.kiesjekraam.amsterdam.nl/profile/2019073101/
EVI aangezet  (soll, aangemeld voor woensdag)

**Comment by Carlio75** [comment]
Check op donderdag 3 december

Gaat niet goed, bij bak AAN en evi AAA gaat het wel goed, maar bij een van twee-en aan gaat het niet goed.

BAK en EVI aangezet (staat op bakplek)
https://acc.kiesjekraam.amsterdam.nl/ondernemer/2008020401/algemene-voorkeuren/126/
--> bak AAN en evi AAN in toewijzingen en afwijzingen overzicht --> gaat niet goed

https://acc.kiesjekraam.amsterdam.nl/ondernemer/1999010403/algemene-voorkeuren/126/
--> bak AAN en evi AAN in toewijzingen en afwijzingen overzicht --> gaat niet goed


EVI aangezet (staat op gewone plek)
https://acc.kiesjekraam.amsterdam.nl/ondernemer/2006011003/algemene-voorkeuren/126/
--> bak staat op UIT en evi staat op UIT in toewijzingen en afwijzingen overzicht --> gaat niet goed

https://acc.kiesjekraam.amsterdam.nl/ondernemer/1991050304/algemene-voorkeuren/126/
--> bak staat op UIT en evi staat op UIT in toewijzingen en afwijzingen overzicht --> gaat niet goed

EVI aangezet (soll, aangemeld voor woensdag)
https://acc.kiesjekraam.amsterdam.nl/profile/1966061702/
--> bak staat op UIT en evi staat op UIT in toewijzingen en afwijzingen overzicht --> gaat niet goed

https://acc.kiesjekraam.amsterdam.nl/profile/2019073101/
--> geen settings te zien, dus ik heb denk ik dit profiel na aanpassen niet opgeslagen.

**Comment by evaleffef** [comment]
Braindump: Het lijkt er een beetje op dat als een ondernemer GEEN keuze heeft gemaakt voor een branche in het profiel, de overige instellingen tijdens het moment van indelen niet zichtbaar zijn.

Wat ik zou willen weten:
- waar vandaan komt de data die ik zie in toewijzingen/afwijzingen;
- wordt de data wel opgeslagen, maar niet getoond?
- waarom wordt de data niet opgeslagen (tijdens de indeling om 21.00 uur)
