### ISSUE TITLE
Centraal opslaan markten data

### ISSUE THREAD

**Issue by Carlio75** [Amsterdam/makkelijkemarkt-kiesjekraam#735]
Naast het aanpassen van de data lokaal moet dit ook teruggeschreven worden naar de database.

Next step: deze changes moeten te zien zijn in KjK.

let op met testen:
- markten aanmaken
- markten aanpassen
- dagen toevoegen
- kramen aanpassen en toevoegen

**Comment by Carlio75** [comment]
Dit hebben hebben we getest door markten aan te passen en in een andere browser/computer te openen maar de changes worden niet centraal opgeslagen.

**Comment by Carlio75** [comment]
@milovanderlinden kruimelpad op scherm werkt niet goed. URL wel goed, kruimel
<img width="819" alt="Screenshot 2021-01-11 at 12 40 04" src="https://user-images.githubusercontent.com/64955526/104178316-683a7600-540a-11eb-9dc6-66a04704121f.png">
<img width="1034" alt="Screenshot 2021-01-11 at 12 39 53" src="https://user-images.githubusercontent.com/64955526/104178318-68d30c80-540a-11eb-882a-9aee333843f5.png">

pad toont verkeerd.

**Comment by Carlio75** [comment]
@milovanderlinden opslaan werkt nog niet goed. we maken markten aan maar die verdwijnen en kunnen we later niet opslaan.

**Comment by Carlio75** [comment]
@milovanderlinden verwijderen van dagen werkt niet. We gooien hem weg maar hij blijft staan bij refresh van de pagina.

**Comment by milovanderlinden** [comment]
Ik heb het opslaan tijdelijk uitgezet. Wat betreft het verkeerde pad; je gebruikt een streepje in de markt naam, dat mag niet; daardoor valt alles om. Ik zal zorgen dat dat niet meer kan.
