### ISSUE TITLE
toe en afwijzingen ook tonen in de wenfase.

### ISSUE THREAD

**Issue by Carlio75** [Amsterdam/makkelijkemarkt-kiesjekraam#755]

**Comment by Carlio75** [comment]
In  de wenperiode toont Kies je Kraam niet de toe- en afwijzigen. Dit is een bug die asp gefix moet worden. 
Bijgesloten voorbeeld van de Dappermarkt die in wenperiode staat en niets toont.
En een voorbeeld van de Van der Pek in live fase die wel de toe- en afwijzigen toont.

Dit heeft ooit wel gewerkt, zie https://github.com/Amsterdam/fixxx-pakjekraam/issues/613

![Screenshot 2020-11-09 at 11 53 17](https://user-images.githubusercontent.com/64955526/98533107-d6d04b80-2282-11eb-9184-2f785f739c1f.png)
![Screenshot 2020-11-09 at 11 53 23](https://user-images.githubusercontent.com/64955526/98533117-d932a580-2282-11eb-9dfa-c8d3b7105a70.png)
![Screenshot 2020-11-09 at 11 53 55](https://user-images.githubusercontent.com/64955526/98533119-d9cb3c00-2282-11eb-8946-927453a3466d.png)
![Screenshot 2020-11-09 at 11 54 02](https://user-images.githubusercontent.com/64955526/98533121-da63d280-2282-11eb-84e4-a08a59fc82cb.png)

**Comment by tjoekbezoer** [comment]
De functionaliteit heeft nooit naar behoren gewerkt. In het genoemde ticket wordt melding gemaakt van een verschil in weergave tussen ondernemer vs marktmeester. De ondernemer mag enkel live markten zien, de marktmeester mag live, wenperiode en activatie zien. De code heeft echter altijd enkel live markten weergegeven. Zie snippet hieronder van 16 december, de datum van toevoeging:

https://github.com/Amsterdam/fixxx-pakjekraam/blob/d09e1fd9ed2aac3651d60364ed442445794adb17/src/routes/ondernemer.ts#L69

Ik pas dit aan zodat dit enkel gebeurd bij ondernemers, zodat marktmeester alle 3 de fases zichtbaar krijgen.

**Comment by Carlio75** [comment]
Bijna zoals bedoeld. Getest en het systeem toont nu ook informatie in de wen- en activatie periode.. Alleen nog niet alle info die het zou moeten tonen. 
Ook bij ondernemers die hun profiel niet invullen moeten ook de velden Aantal, Flex, Bak en Evi. Gevuld worden. Dus als daar niets is aangegeven door de ondernemer zou Aantla het aantal plekken moeten tonen die aan de VPH gekoppeld staan of default bij de SOLL. Flex moet dan op - staan, Bak en Evi op UIT. Branche en voorkeuren kunnen leeg blijven.

Voorbeeld van de Van der Pek (live fase) waar de ondernemer op een aantal dagen zijn profiel wel heeft ingevuld en andere dagen niet. Voorbeeld van ACC
<img width="1046" alt="Screenshot 2020-11-11 at 09 51 59" src="https://user-images.githubusercontent.com/64955526/98798901-b3d2a280-240e-11eb-95a8-ce5950dadd57.png">
 
Hieronder de Ten Kate dinsdag die in wenfase staat waar dus bij deze ondernemer alleen de toewijzing wordt getoond.  Voorbeeld van ACC
<img width="1033" alt="Screenshot 2020-11-11 at 11 13 23" src="https://user-images.githubusercontent.com/64955526/98799148-06ac5a00-240f-11eb-9fac-56fdd58964cb.png">
