### ISSUE TITLE
verplicht maken van invoeren branche door ondernemer in eigen profiel

### ISSUE THREAD

**Issue by Carlio75** [Amsterdam/makkelijkemarkt-kiesjekraam#758]
@Karlijn Moll even een vraag! Is het mogelijk om ondernemers te verplichten hun profiel in te vullen? Dat ze bijvoorbeeld niet verder kunnen in kjk als ze hun profiel niet hebben ingevuld?

De reden achter deze wens komt voort uit het feit dat ondernemers vaak niet hun branche invoeren. Daardoor is er geen check op maximering mogelijk. Om een zo gevarieerd mogelijke markt aan te bieden is maximering belangrijk.
Het is momenteel niet mogelijk deze branche info vanuit Mercato mee te geven aan Kies je Kraam.

Wens is dus:
- verplicht maken door ondernemer om branche in te voeren bijvoorbeeld door te voorkomen dat hij/zij zich daarna kan aanmelden voor markten

**Comment by Carlio75** [comment]
let op: in eerste instantie was ook nog de wens om het aanpassen van de branche alleen door de makrtmeesterrol te laten plaatsvinden. Die wens is vervallen.

**Comment by evaleffef** [comment]
Sollicitanten moeten zich niet kunnen aanmelden als in hun profiel de branche leeg is. 

Dit geldt in eerste instantie NIET voor VPH's.

**Comment by evaleffef** [comment]
> U hebt uw koopwaar nog niet doorgegeven in het marktprofiel, daarom kunt u niet aanmelden voor deze markt.
