### ISSUE TITLE
Tonen informatie bij toe- en afwijzingen ook bij niet ingevuld profiel

### ISSUE THREAD

**Issue by Carlio75** [Amsterdam/makkelijkemarkt-kiesjekraam#790]
**= vergelijkbaar issue (in elk geval overlap) als #711** 

Het systeem toont nu ook informatie in de wen- en activatie periode.. Alleen nog niet alle info die het zou moeten tonen.

Ook bij ondernemers die hun profiel niet invullen moeten ook de velden Aantal, Flex, Bak, Evi en Branche gevuld worden. 
Dus het profiel niet is ingevuld door de ondernemer zou aantal het aantal plekken moeten tonen die aan de VPH gekoppeld staan. Bij de sollicitant zou dit dan op de default moeten staan. 
Flex en Branche moeten dan op - staan. Bak en Evi op UIT. Voorkeuren kan leeg blijven.

https://acc.kiesjekraam.amsterdam.nl/ondernemer/2019052204/toewijzingen-afwijzingen
Bovenstaande ondernemer heeft een aantal dagen WEL haar profiel ingevuld en een aantal dagen NIET. OOk bij de niet ingevulde dagen zouden de velden:
Aantal
Flex
Bak
Evi 
Branche

<img width="1025" alt="Screenshot 2020-12-01 at 12 28 04" src="https://user-images.githubusercontent.com/64955526/100735214-23fe9380-33d1-11eb-99f9-e7916caeb540.png">

**Comment by evaleffef** [comment]
Fijn als het er zo uitziet

![image](https://user-images.githubusercontent.com/39556722/103885160-e1229080-50df-11eb-8777-295a79edb1f4.png)
