### ISSUE TITLE
Input controle inbouwen in bewerk de markt.

### ISSUE THREAD

**Issue by milovanderlinden** [Amsterdam/makkelijkemarkt-kiesjekraam#796]

**Comment by milovanderlinden** [comment]
Issue is niet uitgeschreven. Ik wil graag weten welke input moet worden gecontroleerd. Nu geeft de achterkant een fout als een json structuur niet klopt, maar wat willen jullie nog meer valideren? Graag uitwerken.

**Comment by Carlio75** [comment]
@milovanderlinden ik ga hier even goed over nadenken
