### ISSUE TITLE
Indelingslink is niet zichtbaar direct na 21.00 uur

### ISSUE THREAD

**Issue by evaleffef** [Amsterdam/makkelijkemarkt-kiesjekraam#799]

**Comment by tomootes** [comment]
@evaleffef wat willen we hier na negen uur laten zien op de dag van de indeling zelf? Moet hij dan wel of niet meer te zien zijn? Zo maar even bespreken.

**Comment by tomootes** [comment]
Besproken met @evaleffef. We gaan dit simpeler organiseren. De indeling wordt getoond of de dag voor de indeling na het indelingstijdstip of op de dag van de indeling zelf.
