### ISSUE TITLE
EVI tintje valt niet echt als geen branche aan de kraam hebt hangen

### ISSUE THREAD

**Issue by Carlio75** [Amsterdam/makkelijkemarkt-kiesjekraam#801]
Als je een EVI aan een kraam hangt maar geen branche geselecteerd hebt is de tint grijs wel erg licht, kan die iets donkerder?
Voorbeeld, kraam 4 heeft een EVI.

<img width="564" alt="Screenshot 2020-12-28 at 17 42 02" src="https://user-images.githubusercontent.com/64955526/103229971-7e3d3680-4934-11eb-950a-9f58a1b8ae13.png">

**Comment by milovanderlinden** [comment]
Graag jullie advies. Welke kleur adviseren jullie voor kramen zonder toewijzing?
