### ISSUE TITLE
branches die al gebruikt zijn in branchelijst wel zien maar niet kunnen aanklikken - grey out

### ISSUE THREAD

**Issue by Carlio75** [Amsterdam/makkelijkemarkt-kiesjekraam#802]
Als je al branches hebt gekozen en toegevoegd aan je overall branchelijst voor de markt is het fijn als je die nog wel in je lijst ziet maar je ze niet meer kan selecteren.
De lijst vanuit de markt bevat namelijk dubbelingen, dus voor het gemak is het handig als je als gebruiker ziet dat een branche al door je is geselecteerd voor die markt.

Hieronder heb ik branche 103 al toegeveogd en is hij uit de lijst, maar met name als je meer branches hebt teogeveogd is het overzicht weg.
<img width="958" alt="Screenshot 2020-12-28 at 17 47 24" src="https://user-images.githubusercontent.com/64955526/103230090-d7a56580-4934-11eb-9bd6-ac07e72f4eb6.png">

**Comment by milovanderlinden** [comment]
Goeie! Inschatting: 4u werk.

**Comment by Carlio75** [comment]
Anders opgelost. De al geselecteerde branches zijn nu niet meer te zien in de lijst.
