### ISSUE TITLE
brancelijst - code intype en auto aanvul NAAST een pulldown.

### ISSUE THREAD

**Issue by Carlio75** [Amsterdam/makkelijkemarkt-kiesjekraam#803]
Als je een branche teoveogd is het handig als je kan beginnen met 10 en dan branche 101, 102, 103 etc worden getoond. Dat is sneller werken. Daarnaast moet je uiteraard ook de volledige of een gedeelte van de code in kunnen voeren. 
Dus select en auto complete in het veld.

<img width="796" alt="Screenshot 2020-12-28 at 17 49 56" src="https://user-images.githubusercontent.com/64955526/103230210-24893c00-4935-11eb-829e-b1b69acd8ef2.png">

**Comment by milovanderlinden** [comment]
Kan ik naar kijken. Inschatting: 4u werk.

**Comment by milovanderlinden** [comment]
Deze was zo makkelijk te implementeren dat ik dit vast heb uitgevoerd. Was letterlijk een woord toevoegen aan de `<Select>` component.

**Comment by milovanderlinden** [comment]
Deze mag je op opgelost zetten in sprint 5
