### ISSUE TITLE
plusje om extra rij toe te voegen ontbreekt

### ISSUE THREAD

**Issue by Carlio75** [Amsterdam/makkelijkemarkt-kiesjekraam#804]
Het plusje onderaan de rij om een tweede, of derde etc rij toe te voegen is verdwenen.

<img width="731" alt="Screenshot 2020-12-28 at 17 51 12" src="https://user-images.githubusercontent.com/64955526/103230274-4f739000-4935-11eb-8d6a-b7eccf2d4a42.png">

**Comment by milovanderlinden** [comment]
Inschatting: 1u
