### ISSUE TITLE
Scrolling bij lange rijen is niet handig

### ISSUE THREAD

**Issue by Carlio75** [Amsterdam/makkelijkemarkt-kiesjekraam#805]
Als je een lange rij maakt is het niet handig dat je aan het einde v an de rij steeds moet scrollen om bij het plusje te komen om een nieuwe kraam toe te voegen.
Is er een manier te bedenken dat je focus automatisch naar het einde van de rij gaat? 

hier gaat het nog lekker.
<img width="1157" alt="Screenshot 2020-12-28 at 17 53 19" src="https://user-images.githubusercontent.com/64955526/103230426-b2652700-4935-11eb-9820-1fd83b51ad56.png">

dit is niet meer handig
<img width="1185" alt="Screenshot 2020-12-28 at 17 53 27" src="https://user-images.githubusercontent.com/64955526/103230442-c0b34300-4935-11eb-8916-cde69e0b8fcd.png">

**Comment by milovanderlinden** [comment]
Dit is een cosmetisch item dat veel tijd zou kunnen kosten. We kunnen bijvoorbeeld van horizontaal naar verticaal switchen; of ik kan zaken inbouwen om naar de volgende regel te gaan. Maar welke richting we ook kiezen, het wordt kostbaar qua tijd.

**Comment by milovanderlinden** [comment]
Maar ik sta uiteraard open voor alle tips!
