### ISSUE TITLE
Tabblad naam kan geen spaties, dat moet wel

### ISSUE THREAD

**Issue by Carlio75** [Amsterdam/makkelijkemarkt-kiesjekraam#806]
Als je een naam aanmaakt voor een tabblad kan je geen spaties doen.
Dit is wel een wens.

Wat is als prefill krijg
<img width="363" alt="Screenshot 2020-12-28 at 17 56 06" src="https://user-images.githubusercontent.com/64955526/103230653-41723f00-4936-11eb-9e8d-6edd7fd138a1.png">

Wat ik zelf in mag voeren

<img width="381" alt="Screenshot 2020-12-28 at 17 56 13" src="https://user-images.githubusercontent.com/64955526/103230652-40d9a880-4936-11eb-911c-fad714ac1e77.png">

**Comment by milovanderlinden** [comment]
Ong. 30 minuten werk.

**Comment by milovanderlinden** [comment]
Opgelost, kan in sprint 5 er bij.
