### ISSUE TITLE
Er komen twee <> in het vakjes als je het leeg probeert te maken met de backspace.

### ISSUE THREAD

**Issue by Carlio75** [Amsterdam/makkelijkemarkt-kiesjekraam#807]
Als je het veld leeg probeert te maken komen er 1 of 2 <> in die je niet kan verwijderen maar die je zelf ook niet hebt ingevuld.

<img width="398" alt="Screenshot 2020-12-28 at 17 55 57" src="https://user-images.githubusercontent.com/64955526/103230623-315a5f80-4936-11eb-84a9-3fe33085c71d.png">
<img width="417" alt="Screenshot 2020-12-28 at 17 55 51" src="https://user-images.githubusercontent.com/64955526/103230627-31f2f600-4936-11eb-857d-9abda25ee4c8.png">

**Comment by milovanderlinden** [comment]
Is opgelost, mag in sprint 5 geplaatst en worden gesloten.
