### ISSUE TITLE
Marktdag afkorting staat niet los van marktdag volledig uitgeschreven

### ISSUE THREAD

**Issue by Carlio75** [Amsterdam/makkelijkemarkt-kiesjekraam#808]
Er gebeuren wat gekke dingen omdat het veld van de afkorting gekoppeld lijkt te zijn aan de marktnaam.

1: De marktomschrijving neemt KAP over van het afkortingsveld.
<img width="624" alt="Screenshot 2020-12-28 at 18 05 50" src="https://user-images.githubusercontent.com/64955526/103231223-98c4df00-4937-11eb-9a8c-1b86d09c1a7b.png">
<img width="627" alt="Screenshot 2020-12-28 at 18 05 59" src="https://user-images.githubusercontent.com/64955526/103231289-b85c0780-4937-11eb-8760-59fff74d1d51.png">

2:  Verder vult hij Maandag, Dinsdag etc vooraf in, maar het kan ook voorkomen dat we een:
- Boerenmarkt
- Biomarkt
- Antiekmarkt

<img width="590" alt="Screenshot 2020-12-28 at 18 05 44" src="https://user-images.githubusercontent.com/64955526/103231304-c1e56f80-4937-11eb-8b37-0a96c579b2de.png">
<img width="641" alt="Screenshot 2020-12-28 at 18 06 05" src="https://user-images.githubusercontent.com/64955526/103231315-c9a51400-4937-11eb-8cd5-74ff5f58ebbb.png">

Die twee velden moeten echt los van elkaar staan. Ik snap iik niet zo goed waarom het veld met de uitgeschreven marktdag nodig is.

**Comment by milovanderlinden** [comment]
Kleine wijziging; 1 uurtje werk.
